version: '3.7'

# ---------------------------------------------------------------------------- #

services:

  # -------------------------------------------------------------------------- #

  go: &go
    image: docker.io/jancajthaml/go
    tty: true
    volumes:
      - ..:/project
    working_dir: /project
    environment:
      - GOOS
      - GOARCH
      - GOPATH=/go
      - COMPOSE_PROJECT_NAME

  # -------------------------------------------------------------------------- #

  sync:
    <<: *go
    entrypoint:
      - /project/.dev/lifecycle/sync

  # -------------------------------------------------------------------------- #

  version:
    <<: *go
    command:
      - version

  # -------------------------------------------------------------------------- #

  lint:
    <<: *go
    entrypoint:
      - /project/.dev/lifecycle/lint

  # -------------------------------------------------------------------------- #

  sec:
    <<: *go
    entrypoint:
      - /project/.dev/lifecycle/sec

  # -------------------------------------------------------------------------- #

  test:
    <<: *go
    entrypoint:
      - /project/.dev/lifecycle/test

# ---------------------------------------------------------------------------- #
